# .gitlab-ci.yml - GitLab CI/CD
stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

test-backend:
  stage: test
  image: python:3.11
  services:
    - redis:7-alpine
  variables:
    REDIS_URL: redis://redis:6379/0
  script:
    - cd backend
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - pytest tests/ --cov=app
  coverage: '/TOTAL.*\s+(\d+%)$/'

test-frontend:
  stage: test
  image: node:18
  script:
    - cd frontend
    - npm ci
    - npm test -- --coverage --watchAll=false
    - npm run build
  artifacts:
    paths:
      - frontend/build/

build-docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA ./backend
    - docker build -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA ./frontend
    - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA
  only:
    - main

deploy-production:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache curl
  script:
    - curl -X POST $DEPLOY_WEBHOOK_URL
  environment:
    name: production
    url: https://calc.example.com
  only:
    - main
  when: manual
