# backend/docker-compose.yml
name: redis-celery
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    environment:
      FLASK_ENV: "development"
      SECRET_KEY: "your-secret-key-here"
      REDIS_URL: "redis://redis:6379/0"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
      CORS_ORIGINS: "http://localhost:3000"
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
    command: celery -A celery_worker.celery worker --loglevel=info

volumes:
  redis_data:
