# backend/docker-compose.yml
name: rework-test
services:
  redis:
    image: redis:8.2.1-bookworm
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    environment:
      FLASK_ENV: "development"
      SECRET_KEY: "your-secret-key-here"
      REDIS_URL: "redis://redis:6379/0"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
      CORS_ORIGINS: "http://localhost:3000"
    depends_on:
      - redis
      - mysql
    volumes:
      - ./app:/app/app
    command: celery -A celery_worker.celery worker --loglevel=info

  flower:
    image: mher/flower:2.0
    command: celery flower --address='0.0.0.0' --port=5002 broker-api="redis://redis:6379/0"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    ports:
      - 5002:5002
    depends_on:
      - redis
      - celery

  mysql:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "development"
    ports:
      - "3306:3306"

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web console
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345 # change in prod
    volumes:
      - ./docker/minio-data:/data
    restart: unless-stopped

volumes:
  redis_data:
  mysql_data:
