# backend/docker-compose.yml

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

  backend:
    build: .
    ports:
      - "5000:5000"
    env_file: ".env"
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
    command: python run.py

  celery:
    build: .
    env_file: ".env"
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
    command: celery -A celery_worker.celery worker --loglevel=info

volumes:
  redis_data:
