# monitoring/prometheus-config.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "flask-backend"
    static_configs:
      - targets: ["backend:5000"]
    metrics_path: "/metrics"

  - job_name: "celery-exporter"
    static_configs:
      - targets: ["celery-exporter:9808"]

  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]
